@startuml
'https://plantuml.com/class-diagram

class Item {
    date
    description
    status

    gets()
    sets()
    toString()
}

class ToDoList {
    ArrayList<Item> todo
    String title

    searchItem()
    addItem()
    removeItem()
    displayList(int)
}

class ToDo {
    main()
    start()
}

class ToDoController {
}

class ToDoView {
}

ToDo--ToDoView
ToDo--ToDoController
ToDo*--ToDoList : at least 100 <
ToDoList*--Item : at least 100 <
javafx.Application<|---ToDo

@enduml